# Generated by Django 4.0.5 on 2023-07-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_Generator', '0002_rename_customer_name_invoice_customername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceNo',
            new_name='invoice_no',
        ),
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='unitPrice',
            new_name='unit_price',
        ),
    ]
